name: pre-commit

on:
  push:
    branches:
      - master
      - develop
    tags:
      - '*'
  pull_request:
    paths:
      - .github/workflows/pre-commit-hooks-test.yml
      - .pre-commit-hooks.yaml
      - tests/pre-commit-hooks/*
      - requirements.txt
      - setup.py

jobs:
  hooks-test:
    runs-on: ubuntu-latest
    name: test hooks
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pre-commit
        run: |
          python -m pip install pre-commit
      - name: Test hooks
        run: |
          ./tests/pre-commit-hooks/test.sh
